subgraphs:
  users:
    routing_url: http://localhost:4001
    schema:
      subgraph_url: http://localhost:4001
  social:
    routing_url: http://localhost:4003
    schema:
      subgraph_url: http://localhost:4003
